---
name: "Dependabot notification on new PR"
on: 
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
    # branches:
    #   - 'dependabot/**'
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          alert-lookup: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Echo metadata
        env:
          CONTEXT: "${{ toJSON(steps.metadata) }}"
        run: echo "$CONTEXT"
  